  CREATE TABLE "GGS_BETALLING" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BETALINGTYPE_ID" NUMBER(*,0), 
	"PAYMENT_DATE" DATE NOT NULL ENABLE, 
	"IMAGE" BLOB, 
	"GEBRUIKER_ID" NUMBER(*,0), 
	"BETALING_STATUS_ID" NUMBER, 
	"AMOUNT" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_PRODUCTEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	"PRIJS" NUMBER(18,2) NOT NULL ENABLE, 
	"VOORRAAD" NUMBER(*,0) NOT NULL ENABLE, 
	"CATEGORIEEN_ID" NUMBER(*,0), 
	"STATUS_ID" NUMBER(*,0), 
	"IMAGE" BLOB, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_ADRES" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ADRES" VARCHAR2(255) NOT NULL ENABLE, 
	"HUISNUMMER" NUMBER(*,0) NOT NULL ENABLE, 
	"WOONWIJK_ID" NUMBER(*,0), 
	"GEBRUIKER_ID" NUMBER(*,0), 
	"NAAM" VARCHAR2(255), 
	"LATITUDE" NUMBER(10,6), 
	"LONGITUDE" NUMBER(10,6), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_AUDIT" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ACTIE" VARCHAR2(255) NOT NULL ENABLE, 
	"GEBRUIKER_ID" NUMBER(*,0), 
	"DATUM" TIMESTAMP (6) NOT NULL ENABLE, 
	"OMSCHRIJVING" NVARCHAR2(255), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_AUT_AUT_PRIVILEGES" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(100), 
	"APEX_PAGE" NUMBER, 
	"APEX_COMPONENT_NAME" VARCHAR2(255), 
	"READ" VARCHAR2(1), 
	"WRITE" VARCHAR2(1), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_AUT_AUT_USR_RLE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"GEBRUIKER_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"VALID_FROM" DATE, 
	"VALID_UNTIL" DATE, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AUT_URE_UK1" UNIQUE ("GEBRUIKER_ID", "ROLE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_BESTELLINGEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"GEBRUIKER_ID" NUMBER(*,0), 
	"DATUM" TIMESTAMP (6) NOT NULL ENABLE, 
	"TOTALBEDRAG" NUMBER(18,2) NOT NULL ENABLE, 
	"BESTELLINGSTATUS_ID" NUMBER(*,0), 
	"ROUTE_ID" NUMBER(*,0), 
	"OMSCHRIJVING" VARCHAR2(255), 
	"ADRES_ID" NUMBER, 
	"BETALING_ID" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_BESTELLINGITEMS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BESTELLING_ID" NUMBER(*,0), 
	"PRODUCT_ID" NUMBER(*,0), 
	"HOEVEELHEID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_BESTELLINGSTATUS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_BETALING_STATUS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_BETALLINGTYPE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_BLOESEIZOEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(*,0), 
	"SEIZOEN_ID" NUMBER(*,0), 
	"RANKING" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_CART" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"GEBRUIKER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"HOEVEELHEID" NUMBER(*,0) DEFAULT 1, 
	"DATUM" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_CATEGORIEEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_GEBRUIKER" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	"FAMILYNAAM" VARCHAR2(255) NOT NULL ENABLE, 
	"WACHTWOORD" VARCHAR2(255) NOT NULL ENABLE, 
	"ROL_ID" NUMBER(*,0), 
	"STATUS_ID" NUMBER(*,0), 
	"ADRES_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(50), 
	"DELETED" CHAR(1), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNIQUE_USERNAME" UNIQUE ("USERNAME")
  USING INDEX  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_KORTINGCODE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"BEDRAG" NUMBER(*,0) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_KORTINGPRODUCTEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(*,0), 
	"CODE_ID" NUMBER(*,0), 
	"STATUS_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_PROMOCODE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"BEDRAG" NUMBER(18,2) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_PROMOPRODUCTEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODE_ID" NUMBER(*,0), 
	"PRODUCT_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_ROLLEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_ROUTE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(*,0), 
	"LATITUDE" NUMBER(10,6), 
	"LONGITUDE" NUMBER(10,6), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_ROUTE_WOONWIJK" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ROUTE_ID" NUMBER NOT NULL ENABLE, 
	"WOONWIJK_ID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_SEIZOEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_STATUS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_TWO_FACTOR_TOKENS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODE" VARCHAR2(255) NOT NULL ENABLE, 
	"EXPIRATION_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"GEBRUIKER_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_VERKOOP" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"AANTAL" NUMBER(*,0) NOT NULL ENABLE, 
	"VERKOOP_DATUM" DATE DEFAULT CURRENT_DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_WOONWIJK" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAAM" VARCHAR2(255) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(*,0), 
	"PRIJS" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GGS_WOONWIJK_ROUTE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ROUTE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"WIJK_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("ROUTE_ID", "WIJK_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GSS_AUT_AUT_RLE_PVE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ROLE_ID" NUMBER, 
	"PVE_ID" NUMBER, 
	"RPE_VALID_FROM" DATE, 
	"RPE_VALID_UNTIL" DATE, 
	"RPE_CREATED_DATE" DATE, 
	"RPE_CREATED_BY" VARCHAR2(50), 
	"RPE_MODIFIED_DATE" DATE, 
	"RPE_MODIFIED_BY" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AUT_RPE_UK1" UNIQUE ("ROLE_ID", "PVE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "HTMLDB_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"OPERATION" VARCHAR2(30), 
	"OPTIONS" VARCHAR2(255), 
	"OBJECT_NODE" VARCHAR2(128), 
	"OBJECT_OWNER" VARCHAR2(128), 
	"OBJECT_NAME" VARCHAR2(128), 
	"OBJECT_ALIAS" VARCHAR2(261), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(128), 
	"OPTIMIZER" VARCHAR2(255), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255), 
	"PARTITION_START" VARCHAR2(255), 
	"PARTITION_STOP" VARCHAR2(255), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000), 
	"FILTER_PREDICATES" VARCHAR2(4000), 
	"PROJECTION" VARCHAR2(4000), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(128)
   ) ;


  CREATE UNIQUE INDEX "AUT_RPE_UK1" ON "GSS_AUT_AUT_RLE_PVE" ("ROLE_ID", "PVE_ID") 
  ;

  CREATE UNIQUE INDEX "AUT_URE_UK1" ON "GGS_AUT_AUT_USR_RLE" ("GEBRUIKER_ID", "ROLE_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478716" ON "GGS_ROLLEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478734" ON "GGS_STATUS" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478738" ON "GGS_ADRES" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478743" ON "GGS_GEBRUIKER" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478749" ON "GGS_WOONWIJK" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478753" ON "GGS_CATEGORIEEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478758" ON "GGS_PRODUCTEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478763" ON "GGS_SEIZOEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478765" ON "GGS_BLOESEIZOEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478770" ON "GGS_BESTELLINGSTATUS" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478774" ON "GGS_BESTELLINGEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478779" ON "GGS_BESTELLINGITEMS" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478784" ON "GGS_BETALLINGTYPE" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478788" ON "GGS_ROUTE" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478792" ON "GGS_BETALLING" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478798" ON "GGS_AUDIT" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478803" ON "GGS_PROMOCODE" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478804" ON "GGS_PROMOCODE" ("CODE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478807" ON "GGS_PROMOPRODUCTEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478813" ON "GGS_KORTINGCODE" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478814" ON "GGS_KORTINGCODE" ("CODE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173478816" ON "GGS_KORTINGPRODUCTEN" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173562567" ON "GGS_GEBRUIKER" ("EMAIL") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173621528" ON "GGS_TWO_FACTOR_TOKENS" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173693048" ON "GGS_ROUTE_WOONWIJK" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173914331" ON "GGS_AUT_AUT_PRIVILEGES" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173914332" ON "GGS_AUT_AUT_PRIVILEGES" ("NAME") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173914349" ON "GSS_AUT_AUT_RLE_PVE" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173914354" ON "GGS_AUT_AUT_USR_RLE" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173920589" ON "GGS_WOONWIJK_ROUTE" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173920590" ON "GGS_WOONWIJK_ROUTE" ("ROUTE_ID", "WIJK_ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00173958652" ON "GGS_VERKOOP" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00174088919" ON "GGS_CART" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00174272975" ON "GGS_BETALING_STATUS" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_IL0362708365C00007$$" ON "GGS_PRODUCTEN" (
  ;

  CREATE UNIQUE INDEX "SYS_IL0362708394C00004$$" ON "GGS_BETALLING" (
  ;

  CREATE UNIQUE INDEX "UNIQUE_USERNAME" ON "GGS_GEBRUIKER" ("USERNAME") 
  ;



   CREATE SEQUENCE  "GGS_CART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;



  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AUT_USER_PRIVILEGES_VW" ("USR_ID", "USR_RLE_ID", "USR_PVE_ID", "USR_USERNAME", "USR_EMAIL", "USR_RLE_NAME", "USR_RLE_DESCRIPTION", "USR_RLE_VALID_FROM", "USR_RLE_VALID_UNTIL", "USR_PVE_NAME", "USR_PVE_APEX_PAGE", "USR_PVE_APEX_COMPONENT_NAME", "USR_PVE_READ", "USR_PVE_WRITE", "USR_PVE_VALID_FROM", "USR_PVE_VALID_UNTIL") AS 
  select  gbr.id                  usr_id              
,       rle.id                  usr_rle_id              
,       pve.id                  usr_pve_id              
-- user details         
,       gbr.username            usr_username            
,       gbr.email               usr_email
-- user role details    
,       rle.naam                usr_rle_name                
,       rle.description         usr_rle_description                
,       ure.valid_from          usr_rle_valid_from
,       ure.valid_until         usr_rle_valid_until
-- priv details
,       pve.name                usr_pve_name              
,       pve.apex_page           usr_pve_apex_page      
,       pve.apex_component_name usr_pve_apex_component_name                  
,       pve.read                usr_pve_read  
,       pve.write               usr_pve_write  
,       rpe.rpe_valid_from          usr_pve_valid_from
,       rpe.rpe_valid_until         usr_pve_valid_until
from    ggs_gebruiker gbr
join    ggs_aut_aut_usr_rle          ure on gbr.id = ure.gebruiker_id  
join    ggs_rollen                   rle on rle.id = ure.role_id  
join    gss_aut_aut_rle_pve          rpe on rle.id = rpe.role_id  
join    ggs_aut_aut_privileges       pve on pve.id = rpe.pve_id;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "KLANTENVIEW" ("ID", "NAAM", "FAMILYNAAM", "WACHTWOORD", "ROL_ID", "STATUS_ID", "ADRES_ID", "USERNAME", "EMAIL", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY", "DELETED") AS 
  SELECT "ID","NAAM","FAMILYNAAM","WACHTWOORD","ROL_ID","STATUS_ID","ADRES_ID","USERNAME","EMAIL","CREATED_DATE","CREATED_BY","MODIFIED_DATE","MODIFIED_BY","DELETED"
FROM GGS_GEBRUIKER
WHERE rol_id = 22;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "KORTINGVIEW" ("ID", "CODE", "BEDRAG", "STATUS_ID") AS 
  select ID,
       CODE,
       BEDRAG,
       STATUS_ID
  from GGS_KORTINGCODE;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MEEST_VERKOCHTE_PRODUCTEN" ("PRODUCT_NAAM", "TOTAAL_VERKOCHT") AS 
  WITH bestelling_items AS (
    SELECT 
        id, 
        TRIM(REGEXP_SUBSTR(omschrijving, '(.+?) \(x[0-9]+\)', 1, LEVEL, NULL, 1)) AS product,
        TO_NUMBER(REGEXP_SUBSTR(omschrijving, '\(x([0-9]+)\)', 1, LEVEL, NULL, 1)) AS aantal
    FROM ggs_bestellingen
    CONNECT BY REGEXP_INSTR(omschrijving, '(.+?) \(x[0-9]+\)', 1, LEVEL) > 0
    AND PRIOR id = id
    AND PRIOR DBMS_RANDOM.VALUE IS NOT NULL 
)
SELECT LOWER(TRIM(product)) AS product_naam, 
       SUM(NVL(aantal, 1)) AS totaal_verkocht
FROM bestelling_items
WHERE product IS NOT NULL
GROUP BY LOWER(TRIM(product))
ORDER BY totaal_verkocht DESC;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ROLLENVIEW" ("ID", "NAAM", "DESCRIPTION", "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY") AS 
  SELECT "ID","NAAM","DESCRIPTION","CREATED_DATE","CREATED_BY","MODIFIED_DATE","MODIFIED_BY"
FROM GGS_rollen;




